volumes:
  distrbute-filesystem:
    external: true

networks:
  distrbute-network:
    external: true

services:
  db:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:16.1
    volumes:
      - ${PWD}/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh:Z,ro
      - distrbute-filesystem:/distrbute-filesystem
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}" ]
      timeout: 10s
      retries: 10
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    networks:
      - distrbute-network
    restart: unless-stopped