volumes:
  distrbute-filesystem:
    external: true

networks:
  distrbute-network:
    external: true

services:
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redislabs/redismod
    hostname: redis
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    networks:
      - distrbute-network
    restart: unless-stopped
    
  redisinsight:
    container_name: redis-insight
    hostname: redis-insight
    image: redislabs/redisinsight:latest
    # restart: always
    ports:
      - '127.0.0.1:8001:8001'
    volumes:
      - ./Users/ajeetraina/data/redisinsight:/db 