// <auto-generated />
using System;
using System.Collections.Generic;
using App.Distrbute.Common;
using App.Distrbute.Common.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ObjectStorage.Sdk.Dtos;
using Socials.Sdk.Dtos;

#nullable disable

namespace App.Distrbute.Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250921203245_Add_Unique_Constraint_To_ExternalPostId")]
    partial class Add_Unique_Constraint_To_ExternalPostId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Distrbute.Common.Models.Brand", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Location>("Location")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DocumentFile>("ProfilePicture")
                        .HasColumnType("jsonb");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandDistributorNicheCorrelation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BrandNicheId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DistributorNicheId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandNicheId");

                    b.HasIndex("DistributorNicheId");

                    b.ToTable("BrandDistributorNicheCorrelations");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandInvite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("BrandInvites");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("EmailId");

                    b.ToTable("BrandMembers");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandNiche", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BrandId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DistributorSocialAccountId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DistributorSocialAccountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BrandNiches");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandSocialAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AccessTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FollowersCount")
                        .HasColumnType("bigint");

                    b.Property<long>("FollowingCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("OAuthTokenKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PostsLastSynced")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProfileLastSynced")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProfileLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("BrandSocialAccounts");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Campaign", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<ContentDocumentFile>("Attachment")
                        .HasColumnType("jsonb");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Budget")
                        .HasColumnType("double precision");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FundingTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Reach")
                        .HasColumnType("double precision");

                    b.Property<UGCDocumentFile>("RulesOfEngagement")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubType")
                        .HasColumnType("text");

                    b.Property<List<DistributorNiche>>("TargetedNiches")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetedPlatforms")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("FundingTransactionId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.CampaignInvite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Ask")
                        .HasColumnType("double precision");

                    b.Property<double>("Bid")
                        .HasColumnType("double precision");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeclinedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DistributorSocialAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Expiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("PostSubmitted")
                        .HasColumnType("boolean");

                    b.Property<long>("Reach")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("DistributorSocialAccountId");

                    b.ToTable("CampaignInvites");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.DistrbuteTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision");

                    b.Property<double?>("AmountAfterCharges")
                        .HasColumnType("double precision");

                    b.Property<double?>("AmountDueDistrbute")
                        .HasColumnType("double precision");

                    b.Property<string>("BrandId")
                        .HasColumnType("text");

                    b.Property<double?>("Charges")
                        .HasColumnType("double precision");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .HasColumnType("jsonb");

                    b.Property<string>("DistributorId")
                        .HasColumnType("text");

                    b.Property<string>("IntegrationChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LedgerActionId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentProcessor")
                        .HasColumnType("text");

                    b.Property<string>("PaymentProcessorClientReference")
                        .HasColumnType("text");

                    b.Property<string>("PaymentProcessorDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SettledDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DistributorId");

                    b.ToTable("DistrbuteTransactions");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Distributor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Location>("Location")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OpenToCollaboration")
                        .HasColumnType("boolean");

                    b.Property<DocumentFile>("ProfilePicture")
                        .HasColumnType("jsonb");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.DistributorNiche", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DistributorSocialAccountId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistributorSocialAccountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DistributorNiches");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.DistributorSocialAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AccessTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("AudienceLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DistributorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExcludeFromContent")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FollowersCount")
                        .HasColumnType("bigint");

                    b.Property<long>("FollowingCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("OAuthTokenKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PostPaidViews")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PostsLastSynced")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProfileLastSynced")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProfileLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ReelPaidViews")
                        .HasColumnType("bigint");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ShortPaidViews")
                        .HasColumnType("bigint");

                    b.Property<long>("StoryPaidViews")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.HasIndex("Platform");

                    b.HasIndex("PostPaidViews");

                    b.HasIndex("ReelPaidViews");

                    b.HasIndex("ShortPaidViews");

                    b.HasIndex("StoryPaidViews");

                    b.ToTable("DistributorSocialAccounts");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Email", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LedgerClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrandSocialAccountId")
                        .HasColumnType("text");

                    b.Property<string>("CampaignInviteId")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DistrbuteTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("DistributorSocialAccountId")
                        .HasColumnType("text");

                    b.Property<Embedding>("Embedding")
                        .HasColumnType("jsonb");

                    b.Property<string>("ExternalPostId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostApprovalStatus")
                        .HasColumnType("text");

                    b.Property<string>("PostPayoutStatus")
                        .HasColumnType("text");

                    b.Property<string>("PostStatus")
                        .HasColumnType("text");

                    b.Property<string>("PostValuationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("BrandSocialAccountId");

                    b.HasIndex("CampaignInviteId");

                    b.HasIndex("DistrbuteTransactionId");

                    b.HasIndex("DistributorSocialAccountId");

                    b.HasIndex("ExternalPostId")
                        .IsUnique();

                    b.HasIndex("PostValuationId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.PostValuation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("AuthenticityScore")
                        .HasColumnType("double precision");

                    b.Property<long>("CommentCount")
                        .HasColumnType("bigint");

                    b.Property<double>("ConversionScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("EngagementDepthRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("EngagementRate")
                        .HasColumnType("double precision");

                    b.Property<long>("EstimatedConversions")
                        .HasColumnType("bigint");

                    b.Property<long>("FollowersCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<long>("QuoteCount")
                        .HasColumnType("bigint");

                    b.Property<long>("SavedCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ShareCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.Property<double>("WeightedEngagementScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("PostMetrics");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.SuspenseWallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DistributorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.ToTable("SuspenseWallets");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Wallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("text");

                    b.Property<string>("BrandId")
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DistributorId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderLogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("RecipientCode")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DistributorId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Persistence.Sdk.Models.Outbox", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Brand", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandDistributorNicheCorrelation", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.BrandNiche", "BrandNiche")
                        .WithMany()
                        .HasForeignKey("BrandNicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Distrbute.Common.Models.DistributorNiche", "DistributorNiche")
                        .WithMany()
                        .HasForeignKey("DistributorNicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandNiche");

                    b.Navigation("DistributorNiche");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandInvite", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandMember", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Distrbute.Common.Models.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Email");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandNiche", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Brand", null)
                        .WithMany("Niches")
                        .HasForeignKey("BrandId");

                    b.HasOne("App.Distrbute.Common.Models.DistributorSocialAccount", null)
                        .WithMany("ExcludeFromNiche")
                        .HasForeignKey("DistributorSocialAccountId");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.BrandSocialAccount", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Campaign", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Distrbute.Common.Models.DistrbuteTransaction", "FundingTransaction")
                        .WithMany()
                        .HasForeignKey("FundingTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("FundingTransaction");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.CampaignInvite", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Distrbute.Common.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Distrbute.Common.Models.DistributorSocialAccount", "DistributorSocialAccount")
                        .WithMany()
                        .HasForeignKey("DistributorSocialAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Campaign");

                    b.Navigation("DistributorSocialAccount");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.DistrbuteTransaction", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("App.Distrbute.Common.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId");

                    b.Navigation("Brand");

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Distributor", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.DistributorNiche", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.DistributorSocialAccount", null)
                        .WithMany("Niches")
                        .HasForeignKey("DistributorSocialAccountId");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.DistributorSocialAccount", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Post", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Distrbute.Common.Models.BrandSocialAccount", "BrandSocialAccount")
                        .WithMany()
                        .HasForeignKey("BrandSocialAccountId");

                    b.HasOne("App.Distrbute.Common.Models.CampaignInvite", "CampaignInvite")
                        .WithMany()
                        .HasForeignKey("CampaignInviteId");

                    b.HasOne("App.Distrbute.Common.Models.DistrbuteTransaction", "DistrbuteTransaction")
                        .WithMany()
                        .HasForeignKey("DistrbuteTransactionId");

                    b.HasOne("App.Distrbute.Common.Models.DistributorSocialAccount", "DistributorSocialAccount")
                        .WithMany()
                        .HasForeignKey("DistributorSocialAccountId");

                    b.HasOne("App.Distrbute.Common.Models.PostValuation", "PostValuation")
                        .WithMany()
                        .HasForeignKey("PostValuationId");

                    b.Navigation("Brand");

                    b.Navigation("BrandSocialAccount");

                    b.Navigation("CampaignInvite");

                    b.Navigation("DistrbuteTransaction");

                    b.Navigation("DistributorSocialAccount");

                    b.Navigation("PostValuation");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.SuspenseWallet", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Wallet", b =>
                {
                    b.HasOne("App.Distrbute.Common.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("App.Distrbute.Common.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId");

                    b.Navigation("Brand");

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.Brand", b =>
                {
                    b.Navigation("Niches");
                });

            modelBuilder.Entity("App.Distrbute.Common.Models.DistributorSocialAccount", b =>
                {
                    b.Navigation("ExcludeFromNiche");

                    b.Navigation("Niches");
                });
#pragma warning restore 612, 618
        }
    }
}
